"""
Ray Tune driver for TransVOD / Deformable-DETR fine-tuning.

Usage:
    python -u tune_transvod.py

What it does:
    - Loads the base config from configs/custom_small.yaml.
    - Defines a search space over the hyperparameters that actually move
      small-object AP (lr, lr_backbone, weight_decay, clip_max_norm,
      dropout, num_queries, lr_linear_proj_mult, loss coefficients,
      focal_alpha).
    - Each trial runs the same per-epoch train+evaluate loop as main.py and
      reports `eval/AP` (COCO mAP @[.5:.95]) at the end of every epoch.
    - ASHAScheduler kills trials that lag behind the leaderboard early so
      compute is not wasted on bad configurations.

Notes:
    - Each trial uses 1 GPU. Adjust `resources_per_trial` and
      `num_samples` for your hardware.
    - `max_iters` is honoured per epoch -- keep it small for tuning so each
      trial finishes in minutes. Bump it (or remove it from the config)
      before the final, full retrain.
    - Trial directories live under `RAY_RESULTS_DIR` (default ./ray_results).
      The best config is saved as `best_config.json` next to this script.
"""

from __future__ import annotations

import json
import os
import random
from pathlib import Path

import numpy as np
import torch
import yaml
from torch.utils.data import DataLoader

from ray import tune
from ray.tune.schedulers import ASHAScheduler
from ray.tune.search.optuna import OptunaSearch

try:
    # Ray >= 2.0
    from ray.air.integrations.mlflow import MLflowLoggerCallback
except ImportError:  # pragma: no cover
    # Older Ray
    from ray.tune.integration.mlflow import MLflowLoggerCallback

from datasets import build_dataset, get_coco_api_from_dataset
from main import get_args_parser, load_config_file
from models import build_model


PROJECT_ROOT = Path(__file__).resolve().parent
BASE_CONFIG = PROJECT_ROOT / "configs" / "custom_small.yaml"
RAY_RESULTS_DIR = PROJECT_ROOT / "ray_results"
TUNE_EPOCHS = 6                 # epochs per trial during tuning
TUNE_MAX_ITERS = 400            # iters per epoch during tuning (small for speed)
NUM_SAMPLES = 16                # number of trial configs to draw
GRACE_PERIOD = 2                # ASHA: min epochs before a trial can be killed
GPUS_PER_TRIAL = 1
CPUS_PER_TRIAL = 4

# --- MLflow ---
# Defaults match configs/custom_small.yaml. Override via env vars without
# editing the file.
MLFLOW_TRACKING_URI = os.environ.get(
    "MLFLOW_TRACKING_URI", "http://127.0.0.1:5000")
MLFLOW_EXPERIMENT_NAME = os.environ.get(
    "MLFLOW_EXPERIMENT_NAME", "TransVOD_custom_small_tune")

# Live-updating "best so far" config. Overwritten atomically every time a
# trial reports a higher AP. Drop-in runnable: `python main.py --config <this>`.
BEST_CONFIG_YAML = PROJECT_ROOT / "configs" / "custom_small_best.yaml"


class BestConfigYamlCallback(tune.Callback):
    """Watches every `tune.report` call. If a trial's AP beats the running
    best, atomically rewrites BEST_CONFIG_YAML with base config + that
    trial's overrides."""

    def __init__(self, base_config_path: Path, output_path: Path):
        self.base_config_path = base_config_path
        self.output_path = output_path
        self.best_ap = float("-inf")
        self.best_trial_id = None

    def on_trial_result(self, iteration, trials, trial, result, **info):
        ap = result.get("AP")
        if ap is None or not isinstance(ap, (int, float)):
            return
        # NaN safety: NaN > anything is False, so this naturally skips.
        if ap <= self.best_ap:
            return
        self.best_ap = float(ap)
        self.best_trial_id = trial.trial_id
        self._write_yaml(trial.config, result)
        print(f"[best-yaml] AP={ap:.4f} trial={trial.trial_id} -> {self.output_path}")

    def _write_yaml(self, trial_config: dict, result: dict):
        merged = yaml.safe_load(self.base_config_path.read_text()) or {}
        for k, v in trial_config.items():
            merged[k] = v.item() if hasattr(v, "item") else v

        ap = result.get("AP", float("nan"))
        ap50 = result.get("AP50", float("nan"))
        ap75 = result.get("AP75", float("nan"))
        epoch = result.get("epoch", "?")
        header = (
            f"# Auto-generated by tune_transvod.py -- DO NOT EDIT BY HAND.\n"
            f"# Best trial so far: AP={ap:.4f} AP50={ap50:.4f} AP75={ap75:.4f} "
            f"epoch={epoch} trial={self.best_trial_id}\n"
            f"# Base: {self.base_config_path.name}\n"
        )
        body = yaml.safe_dump(merged, sort_keys=False, default_flow_style=False)

        self.output_path.parent.mkdir(parents=True, exist_ok=True)
        tmp = self.output_path.with_suffix(self.output_path.suffix + ".tmp")
        tmp.write_text(header + body)
        os.replace(tmp, self.output_path)


def _build_args(tune_config: dict):
    """Build an argparse Namespace from base YAML + tune overrides."""
    parser = get_args_parser()
    file_cfg = load_config_file(str(BASE_CONFIG))
    valid_dests = {a.dest for a in parser._actions}
    unknown = [k for k in file_cfg.keys() if k not in valid_dests]
    if unknown:
        raise ValueError(f"Unknown keys in {BASE_CONFIG}: {unknown}")
    parser.set_defaults(**file_cfg)

    args = parser.parse_args([])

    for k, v in tune_config.items():
        if not hasattr(args, k):
            raise ValueError(f"Tune config key '{k}' is not a known arg.")
        setattr(args, k, v)

    # Force per-trial settings: short epochs, no MLflow (Ray owns the logs),
    # absolute paths because Ray chdirs into the trial directory.
    args.epochs = TUNE_EPOCHS
    args.max_iters = TUNE_MAX_ITERS
    args.mlflow_enabled = False
    args.mlflow_log_system_metrics = False
    args.output_dir = ""              # checkpoints aren't useful during tuning
    args.distributed = False
    args.coco_path = str((PROJECT_ROOT / args.coco_path).resolve())
    if args.resume:
        args.resume = str((PROJECT_ROOT / args.resume).resolve())
    if args.lr_drop_epochs is None:
        args.lr_drop_epochs = [max(1, args.epochs - 1)]

    return args


def _seed_everything(seed: int):
    torch.manual_seed(seed)
    np.random.seed(seed)
    random.seed(seed)


def _build_optimizer(model, args):
    def match(n, keywords):
        return any(b in n for b in keywords)

    param_dicts = [
        {
            "params": [p for n, p in model.named_parameters()
                       if not match(n, args.lr_backbone_names)
                       and not match(n, args.lr_linear_proj_names)
                       and p.requires_grad],
            "lr": args.lr,
        },
        {
            "params": [p for n, p in model.named_parameters()
                       if match(n, args.lr_backbone_names) and p.requires_grad],
            "lr": args.lr_backbone,
        },
        {
            "params": [p for n, p in model.named_parameters()
                       if match(n, args.lr_linear_proj_names) and p.requires_grad],
            "lr": args.lr * args.lr_linear_proj_mult,
        },
    ]
    if args.sgd:
        return torch.optim.SGD(param_dicts, lr=args.lr, momentum=0.9,
                               weight_decay=args.weight_decay)
    return torch.optim.AdamW(param_dicts, lr=args.lr,
                             weight_decay=args.weight_decay)


def _load_resume_weights(model, args):
    """Mirror main.py's coco_pretrain checkpoint loading: skip class_embed
    and any shape-mismatched tensors."""
    if not args.resume:
        return
    ckpt = torch.load(args.resume, map_location="cpu", weights_only=False)
    tmp = model.state_dict().copy()
    if args.coco_pretrain:
        for k, v in ckpt["model"].items():
            if "class_embed" in k:
                continue
            target = tmp.get(k)
            if target is not None and hasattr(target, "shape") and target.shape != v.shape:
                continue
            tmp[k] = v
    else:
        tmp = ckpt["model"]
    model.load_state_dict(tmp, strict=False)


def train_trial(tune_config):
    """One Ray Tune trial: build model + data, train for TUNE_EPOCHS,
    report COCO AP after every epoch."""
    args = _build_args(tune_config)

    if args.dataset_file in ("vid_single", "coco"):
        from engine_single import evaluate, train_one_epoch
        import util.misc as utils
    else:
        from engine_multi import evaluate, train_one_epoch
        import util.misc_multi as utils

    _seed_everything(args.seed)
    device = torch.device(args.device)

    model, criterion, postprocessors = build_model(args)
    model.to(device)

    train_image_set = "train" if args.dataset_file == "coco" else "train_joint"
    dataset_train = build_dataset(image_set=train_image_set, args=args)
    dataset_val = build_dataset(image_set="val", args=args)
    base_ds = get_coco_api_from_dataset(dataset_val)

    sampler_train = torch.utils.data.RandomSampler(dataset_train)
    sampler_val = torch.utils.data.SequentialSampler(dataset_val)
    batch_sampler_train = torch.utils.data.BatchSampler(
        sampler_train, args.batch_size, drop_last=True)

    data_loader_train = DataLoader(
        dataset_train, batch_sampler=batch_sampler_train,
        collate_fn=utils.collate_fn, num_workers=args.num_workers,
        pin_memory=True)
    data_loader_val = DataLoader(
        dataset_val, args.batch_size, sampler=sampler_val, drop_last=False,
        collate_fn=utils.collate_fn, num_workers=args.num_workers,
        pin_memory=True)

    optimizer = _build_optimizer(model, args)
    lr_scheduler = torch.optim.lr_scheduler.MultiStepLR(optimizer, args.lr_drop_epochs)

    _load_resume_weights(model, args)

    for epoch in range(args.epochs):
        train_stats = train_one_epoch(
            model, criterion, data_loader_train, optimizer, device, epoch,
            args.clip_max_norm, max_iters=args.max_iters, mlflow_log_every=0)
        lr_scheduler.step()

        eval_stats, _ = evaluate(
            model, criterion, postprocessors, data_loader_val, base_ds,
            device, output_dir="")

        # Standard COCO 12-value bbox stats ordering: AP, AP50, AP75, ...
        ap = ap50 = ap75 = float("nan")
        coco_bbox = eval_stats.get("coco_eval_bbox")
        if coco_bbox and len(coco_bbox) >= 3:
            ap, ap50, ap75 = float(coco_bbox[0]), float(coco_bbox[1]), float(coco_bbox[2])

        tune.report({
            "epoch": epoch,
            "AP": ap,
            "AP50": ap50,
            "AP75": ap75,
            "train_loss": float(train_stats.get("loss", float("nan"))),
            "class_error": float(train_stats.get("class_error", float("nan"))),
        })


def build_search_space():
    """Search space focused on the levers that move small-object AP for
    Deformable-DETR fine-tunes. Keep this list short -- every extra dim
    costs trials."""
    return {
        "lr": tune.loguniform(5e-6, 1e-4),
        "lr_backbone": tune.loguniform(5e-7, 1e-5),
        "lr_linear_proj_mult": tune.choice([0.05, 0.1, 0.2]),
        "weight_decay": tune.loguniform(1e-5, 5e-4),
        "clip_max_norm": tune.choice([0.1, 0.5, 1.0]),
        "dropout": tune.uniform(0.0, 0.2),
        "num_queries": tune.choice([100, 300, 500]),
        "cls_loss_coef": tune.uniform(1.0, 4.0),
        "bbox_loss_coef": tune.uniform(2.0, 8.0),
        "giou_loss_coef": tune.uniform(1.0, 4.0),
        "focal_alpha": tune.uniform(0.15, 0.5),
    }


def main():
    RAY_RESULTS_DIR.mkdir(parents=True, exist_ok=True)

    scheduler = ASHAScheduler(
        time_attr="epoch",
        max_t=TUNE_EPOCHS,
        grace_period=GRACE_PERIOD,
        reduction_factor=3,
    )
    search_alg = OptunaSearch()

    tuner = tune.Tuner(
        tune.with_resources(
            train_trial,
            resources={"cpu": CPUS_PER_TRIAL, "gpu": GPUS_PER_TRIAL},
        ),
        param_space=build_search_space(),
        tune_config=tune.TuneConfig(
            metric="AP",
            mode="max",
            scheduler=scheduler,
            search_alg=search_alg,
            num_samples=NUM_SAMPLES,
        ),
        run_config=tune.RunConfig(
            name="transvod_small",
            storage_path=str(RAY_RESULTS_DIR),
            log_to_file=True,
            callbacks=[
                BestConfigYamlCallback(BASE_CONFIG, BEST_CONFIG_YAML),
                MLflowLoggerCallback(
                    tracking_uri=MLFLOW_TRACKING_URI,
                    experiment_name=MLFLOW_EXPERIMENT_NAME,
                    save_artifact=False,   # trial dirs are huge; keep MLflow lean
                    tags={"driver": "ray_tune", "base_config": BASE_CONFIG.name},
                ),
            ],
        ),
    )

    results = tuner.fit()

    best = results.get_best_result(metric="AP", mode="max")
    print("\n=== Best trial ===")
    print(f"AP    : {best.metrics.get('AP')}")
    print(f"AP50  : {best.metrics.get('AP50')}")
    print(f"AP75  : {best.metrics.get('AP75')}")
    print(f"epoch : {best.metrics.get('epoch')}")
    print(f"config: {json.dumps(best.config, indent=2)}")

    out = PROJECT_ROOT / "best_config.json"
    out.write_text(json.dumps({
        "metrics": {k: v for k, v in best.metrics.items()
                    if isinstance(v, (int, float, str))},
        "config": best.config,
    }, indent=2))
    print(f"Wrote {out}")
    if BEST_CONFIG_YAML.exists():
        print(f"Best YAML       : {BEST_CONFIG_YAML}")
    print(f"MLflow tracking : {MLFLOW_TRACKING_URI}")
    print(f"MLflow experiment: {MLFLOW_EXPERIMENT_NAME}")


if __name__ == "__main__":
    os.chdir(PROJECT_ROOT)   # make relative paths in main.py / datasets work
    main()
